services:
  ldap:
    image: osixia/openldap:1.3.0
    hostname: ldap
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "Confluent"
      LDAP_DOMAIN: "confluent.io"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - "$PWD/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom"
    command: "--copy-service"

  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:stable
    ports:
      - "8080:80"
    environment:
      - PHPLDAPADMIN_HTTPS="false"
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    links:
      - ldap
    depends_on:
      - ldap
  db:
    image: mariadb:10
    hostname: db
    container_name: db
    environment:
      #MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_ROOT_PASSWORD:        ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER:                 ${MARIADB_USER}
      MARIADB_PASSWORD:             ${MARIADB_PASSWORD}
      MARIADB_DATABASE:             ${MARIADB_DATABASE}
    restart: unless-stopped
    ports: 
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start --import-realm
    hostname: keycloak
    container_name: keycloak
    depends_on:
      - db
      - ldap
    environment:
      KC_HTTP_ENABLED:        true
      KC_HOSTNAME:             ${KC_HOSTNAME}
      KC_PROXY:                edge
      KEYCLOAK_ADMIN:          ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB:                   mariadb
      KC_DB_URL_HOST:          db
      KC_DB_URL_PORT:          3306
      KC_DB_URL_DATABASE:      ${MARIADB_DATABASE}
      KC_DB_USERNAME:          ${MARIADB_USER}
      KC_DB_PASSWORD:          ${MARIADB_PASSWORD}
    ports:
     - 18080:8080
     - 18443:8443
    restart: unless-stopped
    volumes:
      - "$PWD/keycloak/realm:/opt/keycloak/data/import"

volumes:
  db: